theme = "railwayhistory"

#------------- Regions -------------------------------------------------------

[regions.test]
paths = "paths/test"
rules = "rules/test"

[regions.border]
paths = "paths/border"
rules = "rules/border"


#--- Belgium

[regions.be]
paths = "paths/be"
rules = "rules/be"


#--- Germany

[regions.de-a]
paths = "paths/de/a"
rules = "rules/de/a"
detailed = true

[regions.de-b]
paths = "paths/de/b"
rules = "rules/de/b"

[regions.de-d]
paths = "paths/de/d"
rules = "rules/de/d"

[regions.de-e]
paths = "paths/de/e"
rules = "rules/de/e"

[regions.de-f]
paths = "paths/de/f"
rules = "rules/de/f"

[regions.de-g]
paths = "paths/de/g"
rules = "rules/de/g"

[regions.de-h]
paths = "paths/de/h"
rules = "rules/de/h"

[regions.de-k]
paths = "paths/de/k"
rules = "rules/de/k"

[regions.de-l]
paths = "paths/de/l"
rules = "rules/de/l"

[regions.de-m]
paths = "paths/de/m"
rules = "rules/de/m"

[regions.de-n]
paths = "paths/de/n"
rules = "rules/de/n"

[regions.de-p]
paths = "paths/de/p"
rules = "rules/de/p"

[regions.de-r]
paths = "paths/de/r"
rules = "rules/de/r"

[regions.de-s]
paths = "paths/de/s"
rules = "rules/de/s"

[regions.de-t]
paths = "paths/de/t"
rules = "rules/de/t"

[regions.de-u]
paths = "paths/de/u"
rules = "rules/de/u"

[regions.de-w]
paths = "paths/de/w"
rules = "rules/de/w"


#--- Denmark

[regions.dk]
paths = "paths/dk"
rules = "rules/dk"


#--- France

[regions.fr-0]
paths = "paths/fr/0"
rules = "rules/fr/0"

[regions.fr-1]
paths = "paths/fr/1"
rules = "rules/fr/1"

[regions.fr-2]
paths = "paths/fr/2"
rules = "rules/fr/2"

[regions.fr-3]
paths = "paths/fr/3"
rules = "rules/fr/3"

[regions.fr-4]
paths = "paths/fr/4"
rules = "rules/fr/4"

[regions.fr-5]
paths = "paths/fr/5"
rules = "rules/fr/5"

[regions.fr-8]
paths = "paths/fr/8"
rules = "rules/fr/8"


#--- Great Britain

[regions.gb-a]
paths = "paths/gb/a"
rules = "rules/gb/a"

[regions.gb-e]
paths = "paths/gb/e"
rules = "rules/gb/e"

[regions.gb-l]
paths = "paths/gb/l"
rules = "rules/gb/l"

[regions.gb-m]
paths = "paths/gb/m"
rules = "rules/gb/m"

[regions.gb-n]
paths = "paths/gb/n"
rules = "rules/gb/n"

[regions.gb-s]
paths = "paths/gb/s"
rules = "rules/gb/s"

[regions.gb-w]
paths = "paths/gb/w"
rules = "rules/gb/w"


#--- Luxembourg

[regions.lu]
paths = "paths/lu"
rules = "rules/lu"


#--- The Netherlands

[regions.nl]
paths = "paths/nl"
rules = "rules/nl"


#--- Norway

[regions.no]
paths = "paths/no"
rules = "rules/no"


#--- Russia
#
# Currently only Kaliningrad oblast is included, designated as region KG.

[regions.ru-kg]
paths = "paths/ru/kg"
rules = "rules/ru/kg"
detailed = true


[colors]
el_none_pax        = "90640c"
el_none            = "b0945d"

el_ole_ac_high_pax = "8845aa"
el_ole_ac_high     = "b275d1"

el_ole_ac_low_pax  = "aa4689"
el_ole_ac_low      = "d275b4"

el_ole_dc_high_pax = "a51100"
el_ole_dc_high     = "d15e51"

el_ole_dc_low_pax  = "d05113"
el_ole_dc_low      = "ff7f40"

el_rail_high_pax   = "007e49"
el_rail_high       = "3aa578"

el_rail_four_pax   = "007e49"
el_rail_four       = "89895a"
