
[regions.be]
paths = "paths/be"
rules = "rules/be"

[regions.de-a]
paths = "paths/de/a"
rules = "rules/de/a"
detailed = true

[regions.de-b]
paths = "paths/de/b"
rules = "rules/de/b"

[regions.de-e]
paths = "paths/de/e"
rules = "rules/de/e"

[regions.de-f]
paths = "paths/de/f"
rules = "rules/de/f"

[regions.de-g]
paths = "paths/de/g"
rules = "rules/de/g"

[regions.de-h]
paths = "paths/de/h"
rules = "rules/de/h"

[regions.de-k]
paths = "paths/de/k"
rules = "rules/de/k"

[regions.de-l]
paths = "paths/de/l"
rules = "rules/de/l"

[regions.de-n]
paths = "paths/de/n"
rules = "rules/de/n"

[regions.de-p]
paths = "paths/de/p"
rules = "rules/de/p"

[regions.de-r]
paths = "paths/de/r"
rules = "rules/de/r"

[regions.de-s]
paths = "paths/de/s"
rules = "rules/de/s"

[regions.de-t]
paths = "paths/de/t"
rules = "rules/de/t"

[regions.de-u]
paths = "paths/de/u"
rules = "rules/de/u"

[regions.de-w]
paths = "paths/de/w"
rules = "rules/de/w"

[regions.lu]
paths = "paths/lu"
rules = "rules/lu"

[regions.nl]
paths = "paths/nl"
rules = "rules/nl"

[regions.no]
paths = "paths/no"
rules = "rules/no"

[regions.ru-kg]
paths = "paths/ru/kg"
rules = "rules/ru/kg"
detailed = true
